### ISSUE TITLE
Proxy Connections

### ISSUE THREAD

**Issue by CanisHelix** [slack-ruby/slack-ruby-bot#97] opened 2016-10-03 15:27 UTC
I have a simple Slack Bot working with this, and it's working perfectly fine until I put it on a server at my office that is behind a very restrictive firewall.

Do you know what ports/connections/protocols I need to request opened up to get this Gem working?

Thanks

**Comment by dblock** [comment] 2016-10-03 18:24
Does slack itself work from the network on which the server is on? 

This library uses websockets, so it's all standard HTTPs, port 443, I believe `ws://...`. That said, start figuring out which part actually doesn't work, is it the first `rtm.start` request, or is it establishing the websocket connection? I would start with something as simple as https://github.com/dblock/slack-ruby-client/blob/master/examples/hi_web and then debug from there.

**Comment by edwin-wong-ck** [comment] 2017-08-24 23:53
I'm having the similar issue. IT told me they can see my outbound request goes through the proxy but my inbound does not.  I'm wondering if there's a bug in passing 

Slack::RealTime::Client.config do |config|
  config.websocket_proxy= {origin: 'http://myproxy', user_agent: {'blah blah'}}
end

**Comment by edwin-wong-ck** [comment] 2017-08-25 17:09
It's working for me now, might have had a typo or something:
`Slack::RealTime::Client.configure do |config|
    config.websocket_proxy = {
      origin: 'http://server:port',
      headers: { 'User-Agent' => 'ruby' }
    }`

**Comment by edwin-wong-ck** [comment] 2017-09-13 21:11
There's a bug in here how this is handling https_proxy.  It's working with node slack lib but this lib isn't.

**Comment by dblock** [comment] 2017-09-14 19:00
Care to elaborate @edwin-wong-ck ?

**Comment by edwin-wong-ck** [comment] 2017-09-14 19:53
i think it's a dupe of https://github.com/slack-ruby/slack-ruby-client/issues/110#issuecomment-259266367

**Closed** 2022-08-11 08:16 UTC
Labels: question
