### ISSUE TITLE
Bot does not start properly

### ISSUE THREAD

**Issue by mkarganov** [slack-ruby/slack-ruby-bot#121] opened 2017-03-12 22:22 UTC
Hi, sometimes when I start a bot via ```Bot.run``` log stops at line:
```
D, [2017-03-12T23:11:30.152904 #13321] DEBUG -- Slack::RealTime::Concurrency::Celluloid::Socket#connect!: WebSocket::Driver::Client
```
and nothing happens (bot is offline in a channel), if I restart (not always it succeeds after first restart) it goes ok and next line is:

```
D, [2017-03-12T23:12:00.512804 #13345] DEBUG -- Slack::RealTime::Concurrency::Celluloid::Socket#write: GET /websocket/JcusPEHqlaNbFYuplPuOAyhywrG2vsyCe4woI6OO-WHTcldHSrtPCrrPUhV4JOHbOUcDebnXB7iDhqYCZuuc0qiDrpK7OkGoUOsIqj6FelwJ8DipUMdkVkHMI-H1edIg7IVVnaOjKeMlLw0x7AuyOnqILO8NUMQm4WKoVd5uu-o= HTTP/1.1
Host: mpmulti-09sg.slack-msgs.com
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: 1BZifyP4N4SXHF2X4qPC0w==
Sec-WebSocket-Version: 13
```

Why it can happen?

**Comment by dblock** [comment] 2017-03-13 11:58
It looks like a plain connection failure that will eventually timeout. Could it be an actual network issue? Did you try this on another physical net?

**Comment by mkarganov** [comment] 2017-03-13 12:02
Hi, thank you for you response. Do not have chance to try now. 
What is the timeout value?

**Comment by dblock** [comment] 2017-03-13 12:07
Default timeout is 60 seconds set by Faraday. Since 0.8.0 of slack-ruby-client you can configure it, see https://github.com/slack-ruby/slack-ruby-client.

**Comment by dblock** [comment] 2017-03-13 12:09
Also is this a very large team? Maybe you're just not patient enough and the timeout just needs to be bigger, as it downloads a boatload of data? Try adjusting the timeout to something very short and see if that properly does timeout.

**Comment by mkarganov** [comment] 2017-03-13 12:59
Probably it is not a timeout issue, just waited ~20mins and nothing changes

**Comment by dblock** [comment] 2017-03-13 13:39
Next steps is to write this without all the layers and start debugging from https://github.com/slack-ruby/slack-ruby-client/tree/master/examples/hi_real_time

**Comment by mkarganov** [comment] 2017-03-13 14:37
Ok, using the code from above sometimes I have:
```
I, [2017-03-13T15:34:37.970550 #31729]  INFO -- : post https://slack.com/api/rtm.start
I, [2017-03-13T15:34:38.776441 #31729]  INFO -- Status: 200
```
It is running but nothing happens.

And sometimes it says: ```Successfully connected, welcome ... ```

**Comment by mkarganov** [comment] 2017-03-13 14:40
In if it not says welcome and I try to type anything in channel I get:
```
 [2017-03-13T15:39:05.438483 #31729] ERROR -- : Slack::RealTime::Client::ClientNotStartedError (Slack::RealTime::Client::ClientNotStartedError)
/.../gems/slack-ruby-client-0.8.0/lib/slack/real_time/client.rb:131:in `send_json'
/.../gems/slack-ruby-client-0.8.0/lib/slack/real_time/api/typing.rb:12:in `typing'
(irb):20:in `block in irb_binding'
```

**Comment by dblock** [comment] 2017-03-13 16:22
How big is your team?

**Comment by mkarganov** [comment] 2017-03-13 20:36
less than 50 people

**Comment by dblock** [comment] 2017-03-14 16:20
Try this on another network, wifi, whatever. Just to compare.

**Comment by mkarganov** [comment] 2017-03-16 12:21
Ok, will let you know

**Comment by gsmetal** [comment] 2017-04-11 16:53
I stuck with the same problem. Locally it does not work, it stops at 
```
D, [2017-04-11T19:45:55.889020 #4473] DEBUG -- Slack::RealTime::Concurrency::Celluloid::Socket#connect!: WebSocket::Driver::Client
```
and 
```
I, [2017-04-11T19:50:37.572985 #5283]  INFO -- : post https://slack.com/api/rtm.start
I, [2017-04-11T19:50:38.404373 #5283]  INFO -- Status: 200
``` 
for hi_real_time.

Tried with wifi or ethernet or vpn — no luck. 

But deployed to server it works well. Very difficult to develop my bot without local instance...

**Comment by dblock** [comment] 2017-04-11 23:23
This just sounds like a firewall @gsmetal. Or a much slower connection and a big team? Not sure.

**Comment by gsmetal** [comment] 2017-04-12 08:21
Not really big team (<100 users). What firewall settings I should check? Other websockets work without any problems.

**Comment by dblock** [comment] 2017-04-12 11:49
Not sure @gsmetal, sorry.

**Comment by geoffrey-mantel** [comment] 2017-04-16 15:16
I can confirm that the same thing is happening to me. Not a firewall issue. Not an issue with a big team. My bot is now serving requests for multiple teams. When starting up, occasionally some teams fail to connect with the symptoms indicated above. I'm just starting to debug into this.

**Comment by geoffrey-mantel** [comment] 2017-04-17 15:32
For what it's worth, it seems to be occasionally deadlocking in Celluloid::IO::TCPSocket.new during socket connection in the Celluloid concurrency model of the Slack Ruby Client. Switching the client to EventMachine seems to avoid the deadlock.

@gsmetal  - are you using Celluloid::IO in your Gemfile, or EventMachine? If you switch, does this work-around the problem for you?

**Comment by dblock** [comment] 2017-04-17 22:30
FWIW EventMachine comes with its own slew of problems :(

**Comment by dblock** [comment] 2017-04-17 22:31
Does adding a mutex around some socket connection code help?

**Comment by gsmetal** [comment] 2017-04-18 07:45
> are you using Celluloid::IO in your Gemfile, or EventMachine? If you switch, does this work-around the problem for you?

Yes, I was using celluloid-io. Now tried with eventmachine — yes, it works.

**Comment by dblock** [comment] 2017-04-29 20:53
Slack added `rtm.connect`, which no longer sends any more information than needed to the client on start unlike `rtm.start`. I've implemented support for it in slack-ruby-client in https://github.com/slack-ruby/slack-ruby-client/pull/145, you should try slack-ruby-client#HEAD, it has dramatically improved the memory footprint and connection speed of my [game bot](https://www.playplay.io/) that currently has 385 active teams, maybe it will work better for this issue too?

**Comment by octomancer** [comment] 2017-06-07 14:20
I had a very similar problem when I tried to run the example pongbot.rb script. I switched from celluloid-io to faye-websocket by editing the Gemfile:

```
#gem 'celluloid-io'
gem 'faye-websocket'
```
and my problem disappeared.

My first pass, based on what people have said above was:

```
#gem 'celluloid-io'
gem 'eventmachine'
```

but that generated this error:

`E, [2017-06-07T14:44:07.785015 #76914] ERROR -- : Missing concurrency. Add faye-websocket or celluloid-io to your Gemfile. (Slack::RealTime::Config::NoConcurrencyError)`

which led me to the top version. EventMachine was already installed by this point though, so I can't say if it's needed or not.

**Comment by gsmetal** [comment] 2018-06-18 13:30
After rails and gems update it seems to work now with `celluloid-io`. I have now installed these versions of celluloid:
```   
 celluloid (0.17.3)
      celluloid-essentials
      celluloid-extras
      celluloid-fsm
      celluloid-pool
      celluloid-supervision
      timers (>= 4.1.1)
    celluloid-essentials (0.20.5)
      timers (>= 4.1.1)
    celluloid-extras (0.20.5)
      timers (>= 4.1.1)
    celluloid-fsm (0.20.5)
      timers (>= 4.1.1)
    celluloid-io (0.17.3)
      celluloid (>= 0.17.2)
      nio4r (>= 1.1)
      timers (>= 4.1.1)
    celluloid-pool (0.20.5)
      timers (>= 4.1.1)
    celluloid-supervision (0.20.6)
      timers (>= 4.1.1)
```
and `slack-ruby-bot`: 
```
    slack-ruby-bot (0.11.0)
      hashie
      slack-ruby-client (>= 0.6.0)
    slack-ruby-client (0.11.1)
```

**Comment by dblock** [comment] 2018-09-29 15:06
I'm going to close this, not much actionable here.

**Closed by dblock** 2018-09-29 15:06 UTC
Labels: bug?
