### ISSUE TITLE
Slack bot failed to send messages after a long execution

### ISSUE THREAD

**Issue by peterchinzhen** [slack-ruby/slack-ruby-bot#171] opened 2017-12-06 08:17 UTC
I'm using slack-ruby-bot to imply a command bot, but it always failed to send results.
Looks like connection went expired before getting results.

I've tried with using `Slack::Web::Client.new.chat_postMessage` method in [slack-ruby-client](https://github.com/dblock/slack-ruby-client) but it seems to act as a new bot. The original bot kept down util `Slack::Web::Client.new.chat_postMessage` is called.

I'm wondering if there is any better way to get a new web socket connection when current one goes expired. 

Thanks.

```
2017-12-06T02:34:25.894570 #4] DEBUG -- SlackRubyBot::Client#send_json: {:type=>"message", :id=>2, :text=>"Total number of followers: 3001825", :channel=>"...."}

2017-12-06T02:34:25.895048+00:00 app[web.1]: D, [2017-12-06T02:34:25.894982 #4] DEBUG -- Slack::RealTime::Concurrency::Celluloid::Socket#send_data: {"type":"message","id":2,"text":"Total number of followers: 3001825","channel":"D87PZ30NA"}

2017-12-06T02:34:25.895154+00:00 app[web.1]: D, [2017-12-06T02:34:25.895108 #4] DEBUG -- Slack::RealTime::Concurrency::Celluloid::Socket#write: UF"w2[0d8#Q4!GydKw|w2G!d)V9fL8$Gu)D3)N:1G&|evgsw%J;(Gw|mqrfvlw;

2017-12-06T02:34:25.895643+00:00 app[web.1]: D, [2017-12-06T02:34:25.895580 #4] DEBUG -- Slack::RealTime::Concurrency::Celluloid::Socket#run_loop: end of file reached (EOFError)

2017-12-06T02:34:25.895645+00:00 app[web.1]: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/openssl/buffering.rb:178:in `sysread_nonblock'

2017-12-06T02:34:25.895646+00:00 app[web.1]: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/openssl/buffering.rb:178:in `read_nonblock'

2017-12-06T02:34:25.895647+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:42:in `block in sysread'

2017-12-06T02:34:25.895648+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:390:in `synchronize'

2017-12-06T02:34:25.895648+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:40:in `sysread'

2017-12-06T02:34:25.895649+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:129:in `readpartial'

2017-12-06T02:34:25.895650+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-client-0.10.0/lib/slack/real_time/concurrency/celluloid.rb:51:in `read'

2017-12-06T02:34:25.895651+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-client-0.10.0/lib/slack/real_time/concurrency/celluloid.rb:36:in `block in run_loop'

2017-12-06T02:34:25.895652+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-client-0.10.0/lib/slack/real_time/concurrency/celluloid.rb:36:in `loop'

2017-12-06T02:34:25.895653+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-client-0.10.0/lib/slack/real_time/concurrency/celluloid.rb:36:in `run_loop'

2017-12-06T02:34:25.895654+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-client-0.10.0/lib/slack/real_time/concurrency/celluloid.rb:28:in `connect!'

2017-12-06T02:34:25.895654+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'

2017-12-06T02:34:25.895655+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'

2017-12-06T02:34:25.895656+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'

2017-12-06T02:34:25.895656+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'

2017-12-06T02:34:25.895657+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'

2017-12-06T02:34:25.895657+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'

2017-12-06T02:34:25.895658+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'

2017-12-06T02:34:25.895659+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by dblock** [comment] 2017-12-07 15:48
This RTM connection shouldn't ever expire. Is slack kicking you out somehow? Is this a slow running command? Start with something simpler without any processing, you should be able to both `say` and `client.chat_post...`.

**Comment by dblock** [comment] 2017-12-08 12:27
I think you're blocking the main thread, so you need to be deferring execution to prevent this from happening. This is a duplicate of https://github.com/slack-ruby/slack-ruby-bot/issues/49, which has some recommendations, I'll close this hopefully that issue helps.

**Closed by dblock** 2017-12-08 12:27 UTC
Labels: question
