### ISSUE TITLE
Question about simple_latest

### ISSUE THREAD

**Issue by asheynkman** [slack-ruby/slack-ruby-bot#117] opened 2017-02-22 19:10 UTC
Hi Folks,
 We are facing an issue with a slack bot where upon startup, slack bot keep on restarting  due to the closed socket.  Looks like rtm.start connection downloads metadata which takes too much time and forces slack connection to close. We have tried on setting  { simple_latest: true } in the Slack::RealTime::Client, but it has no effect 

Any ideas or suggestion would be appreciated ?

thank you 

E, [2017-02-22T19:04:23.117699 #1] ERROR -- : Actor crashed!
ThreadError: Target thread must not be current thread
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:37:in `join'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:97:in `join'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:28:in `terminate'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/cell.rb:59:in `terminate'
	/app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-client-0.7.9/lib/slack/real_time/concurrency/celluloid.rb:41:in `run_loop'
	/app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-client-0.7.9/lib/slack/real_time/concurrency/celluloid.rb:28:in `connect!'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
I, [2017-02-22T19:04:23.382691 #1]  INFO -- : BOAT: socket closed, restarting ...

**Comment by dblock** [comment] 2017-02-22 20:55
Is this the same as https://github.com/slack-ruby/slack-ruby-client/issues/134?

**Comment by asheynkman** [comment] 2017-02-22 21:10
Yes its the same issue, thnx

**Comment by dblock** [comment] 2017-02-22 22:01
I'll close it here, the problem is really in slack-ruby-client.

**Closed by dblock** 2017-02-22 22:01 UTC
Labels: bug?
